// Typed access to the official data generated by scripts/build-data.mjs.
import studiesJson from '../data/studies.json';
import atarJson from '../data/atar.json';

export type Grade = 'UG' | 'E' | 'E+' | 'D' | 'D+' | 'C' | 'C+' | 'B' | 'B+' | 'A' | 'A+';

export interface GradeBand {
  grade: Grade;
  /** Lowest score for the grade, or null when no score maps to it. */
  lo: number | null;
  hi: number | null;
  /** Number of students awarded the grade. */
  n: number;
}

export interface GradedAssessment {
  ga: number;
  /** VCAA grade distribution title, e.g. "WRITTEN EXAMINATION 1". */
  title: string;
  /** VCAA assessment summary label, e.g. "Written examination 1". */
  label: string;
  /** Contribution to the study score (%). */
  weight: number;
  /** Oral/written components for Languages examinations. */
  components?: { title: string; weight: number }[];
  /** Maximum score on the VCAA scale for this GA. */
  max: number;
  mean: number;
  sd: number;
  /** Students assessed. */
  n: number;
  grades: GradeBand[];
}

export interface ScalingRow {
  mean: number | null;
  sd: number | null;
  /** Scaled scores for study scores 20, 25, 30, 35, 40, 45, 50. */
  points: number[];
}

export interface Study {
  id: string;
  name: string;
  vet: boolean;
  group: string | null;
  english: boolean;
  equivalents: string[];
  language: boolean;
  /** Keyed by year. "small" means the study was scaled with the "All small LOTEs" row. */
  scaling: Record<string, ScalingRow | 'small'>;
  assessment: { file: string; weightsCode: string; gas: GradedAssessment[] } | null;
}

interface Meta {
  generated: string;
  gaYear: number;
  sources: {
    scaling: Record<string, string>;
    atar: Record<string, string>;
    gradeDistributions: string;
    weights: string;
  };
}

const studiesData = studiesJson as unknown as { meta: Meta; smallLote: Record<string, number[] | null>; studies: Study[] };
const atarData = atarJson as unknown as { meta: Meta; years: Record<string, [number, number][]> };

export const META = studiesData.meta;
export const STUDIES: Study[] = studiesData.studies;
export const SMALL_LOTE = studiesData.smallLote;
export const ATAR_TABLES = atarData.years;
export const YEARS = Object.keys(ATAR_TABLES).map(Number).sort((a, b) => b - a);
export const LATEST_YEAR = YEARS[0];

const byId = new Map(STUDIES.map((s) => [s.id, s]));
export function getStudy(id: string): Study | undefined {
  return byId.get(id);
}

/** Scaling points for a study in a year, resolving small LOTEs. */
export function scalingPoints(study: Study, year: number): number[] | null {
  const row = study.scaling[year];
  if (!row) return null;
  if (row === 'small') return SMALL_LOTE[year] ?? null;
  return row.points;
}

/** The most recent year (<= year) with scaling data for the study. */
export function scalingYearFor(study: Study, year: number): number | null {
  const ys = Object.keys(study.scaling)
    .map(Number)
    .filter((y) => y <= year && scalingPoints(study, y))
    .sort((a, b) => b - a);
  return ys[0] ?? null;
}
